M48
; DRILL file KiCad 10.0.1 date 2026-08-19T00:10:19
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-19T00:10:19+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
%
G90
G05
T1
X-326.95Y-168.09
X-314.95Y-168.09
X-302.95Y-168.09
X-290.95Y-168.09
M30
